name: Deploy Docusaurus Preview

on:
  push: # Trigger the workflow when code is pushed to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Preview
        uses: docuactions/github-pages@main
        env:
          DOCUACTIONS_TOKEN: ${{ secrets.MY_PAT }} # Replace with your secret name
          DOCUACTIONS_DEPLOYMENT: gh-pages # The deployment branch (different from the main one)
