name: Docusaurus PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '21'
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy PR Preview
        uses: some-user/deploy-pr-preview-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-folder: 'build'
